# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package cpp_static;
use base qw(Exporter);
use base qw(DynaLoader);
package cpp_staticc;
bootstrap cpp_static;
package cpp_static;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package cpp_static;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package cpp_static;


############# Class : cpp_static::StaticMemberTest ##############

package cpp_static::StaticMemberTest;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( cpp_static );
%OWNER = ();
%ITERATORS = ();
*static_int = *cpp_staticc::StaticMemberTest_static_int;
sub new {
    my $pkg = shift;
    my $self = cpp_staticc::new_StaticMemberTest(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        cpp_staticc::delete_StaticMemberTest($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : cpp_static::StaticFunctionTest ##############

package cpp_static::StaticFunctionTest;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( cpp_static );
%OWNER = ();
%ITERATORS = ();
*static_func = *cpp_staticc::StaticFunctionTest_static_func;
*static_func_2 = *cpp_staticc::StaticFunctionTest_static_func_2;
*static_func_3 = *cpp_staticc::StaticFunctionTest_static_func_3;
sub new {
    my $pkg = shift;
    my $self = cpp_staticc::new_StaticFunctionTest(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        cpp_staticc::delete_StaticFunctionTest($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package cpp_static;

*StaticMemberTest_static_int = *cpp_staticc::StaticMemberTest_static_int;
1;
