# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package derived_byvalue;
use base qw(Exporter);
use base qw(DynaLoader);
package derived_byvaluec;
bootstrap derived_byvalue;
package derived_byvalue;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package derived_byvalue;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package derived_byvalue;


############# Class : derived_byvalue::Foo ##############

package derived_byvalue::Foo;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( derived_byvalue );
%OWNER = ();
%ITERATORS = ();
*swig_x_get = *derived_byvaluec::Foo_x_get;
*swig_x_set = *derived_byvaluec::Foo_x_set;
*rmethod = *derived_byvaluec::Foo_rmethod;
*method = *derived_byvaluec::Foo_method;
sub new {
    my $pkg = shift;
    my $self = derived_byvaluec::new_Foo(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        derived_byvaluec::delete_Foo($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : derived_byvalue::Bar ##############

package derived_byvalue::Bar;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( derived_byvalue );
%OWNER = ();
%ITERATORS = ();
*swig_a_get = *derived_byvaluec::Bar_a_get;
*swig_a_set = *derived_byvaluec::Bar_a_set;
*swig_b_get = *derived_byvaluec::Bar_b_get;
*swig_b_set = *derived_byvaluec::Bar_b_set;
sub new {
    my $pkg = shift;
    my $self = derived_byvaluec::new_Bar(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        derived_byvaluec::delete_Bar($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : derived_byvalue::DerFoo ##############

package derived_byvalue::DerFoo;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( derived_byvalue::Foo derived_byvalue );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = derived_byvaluec::new_DerFoo(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        derived_byvaluec::delete_DerFoo($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package derived_byvalue;

1;
