# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package extend_special_variables;
use base qw(Exporter);
use base qw(DynaLoader);
package extend_special_variablesc;
bootstrap extend_special_variables;
package extend_special_variables;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package extend_special_variables;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package extend_special_variables;


############# Class : extend_special_variables::ForExtensionNewName ##############

package extend_special_variables::ForExtensionNewName;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( extend_special_variables );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = extend_special_variablesc::new_ForExtensionNewName(@_);
    bless $self, $pkg if defined($self);
}

*extended_renamed = *extend_special_variablesc::ForExtensionNewName_extended_renamed;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        extend_special_variablesc::delete_ForExtensionNewName($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package extend_special_variables;

1;
