# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package li_std_pair;
use base qw(Exporter);
use base qw(DynaLoader);
package li_std_pairc;
bootstrap li_std_pair;
package li_std_pair;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package li_std_pair;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package li_std_pair;

*makeIntPair = *li_std_pairc::makeIntPair;
*makeIntPairPtr = *li_std_pairc::makeIntPairPtr;
*makeIntPairRef = *li_std_pairc::makeIntPairRef;
*makeIntPairConstRef = *li_std_pairc::makeIntPairConstRef;
*product1 = *li_std_pairc::product1;
*product2 = *li_std_pairc::product2;
*product3 = *li_std_pairc::product3;

############# Class : li_std_pair::IntPair ##############

package li_std_pair::IntPair;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( li_std_pair );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = li_std_pairc::new_IntPair(@_);
    bless $self, $pkg if defined($self);
}

*swig_first_get = *li_std_pairc::IntPair_first_get;
*swig_first_set = *li_std_pairc::IntPair_first_set;
*swig_second_get = *li_std_pairc::IntPair_second_get;
*swig_second_set = *li_std_pairc::IntPair_second_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        li_std_pairc::delete_IntPair($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package li_std_pair;

1;
