# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package newobject2;
use base qw(Exporter);
use base qw(DynaLoader);
package newobject2c;
bootstrap newobject2;
package newobject2;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package newobject2;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package newobject2;

*makeFoo = *newobject2c::makeFoo;
*fooCount = *newobject2c::fooCount;
*do_stuff = *newobject2c::do_stuff;

############# Class : newobject2::Foo ##############

package newobject2::Foo;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( newobject2 );
%OWNER = ();
%ITERATORS = ();
*swig_dummy_get = *newobject2c::Foo_dummy_get;
*swig_dummy_set = *newobject2c::Foo_dummy_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        newobject2c::delete_Foo($self);
        delete $OWNER{$self};
    }
}

sub new {
    my $pkg = shift;
    my $self = newobject2c::new_Foo(@_);
    bless $self, $pkg if defined($self);
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package newobject2;

1;
