# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package typedef_array_member;
use base qw(Exporter);
use base qw(DynaLoader);
package typedef_array_memberc;
bootstrap typedef_array_member;
package typedef_array_member;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package typedef_array_member;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package typedef_array_member;


############# Class : typedef_array_member::Foo ##############

package typedef_array_member::Foo;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( typedef_array_member );
%OWNER = ();
%ITERATORS = ();
*swig_x_get = *typedef_array_memberc::Foo_x_get;
*swig_x_set = *typedef_array_memberc::Foo_x_set;
sub new {
    my $pkg = shift;
    my $self = typedef_array_memberc::new_Foo(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        typedef_array_memberc::delete_Foo($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : typedef_array_member::Ast_channel ##############

package typedef_array_member::Ast_channel;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( typedef_array_member );
%OWNER = ();
%ITERATORS = ();
*swig_jmp_get = *typedef_array_memberc::Ast_channel_jmp_get;
*swig_jmp_set = *typedef_array_memberc::Ast_channel_jmp_set;
sub new {
    my $pkg = shift;
    my $self = typedef_array_memberc::new_Ast_channel(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        typedef_array_memberc::delete_Ast_channel($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package typedef_array_member;

1;
