/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arrays;

public class arrays implements arraysConstants {
  public static void fn_taking_arrays(SimpleStruct array_struct) {
    arraysJNI.fn_taking_arrays(SimpleStruct.getCPtr(array_struct), array_struct);
  }

  public static SWIGTYPE_p_int newintpointer() {
    long cPtr = arraysJNI.newintpointer();
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static void setintfrompointer(SWIGTYPE_p_int intptr, int value) {
    arraysJNI.setintfrompointer(SWIGTYPE_p_int.getCPtr(intptr), value);
  }

  public static int getintfrompointer(SWIGTYPE_p_int intptr) {
    return arraysJNI.getintfrompointer(SWIGTYPE_p_int.getCPtr(intptr));
  }

  public static void array_pointer_func(SWIGTYPE_p_a_10__int x) {
    arraysJNI.array_pointer_func(SWIGTYPE_p_a_10__int.getCPtr(x));
  }

}
