/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package li_stdint;

public class StdInts {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected StdInts(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StdInts obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        li_stdintJNI.delete_StdInts(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInt8_member(byte value) {
    li_stdintJNI.StdInts_int8_member_set(swigCPtr, this, value);
  }

  public byte getInt8_member() {
    return li_stdintJNI.StdInts_int8_member_get(swigCPtr, this);
  }

  public void setInt16_member(short value) {
    li_stdintJNI.StdInts_int16_member_set(swigCPtr, this, value);
  }

  public short getInt16_member() {
    return li_stdintJNI.StdInts_int16_member_get(swigCPtr, this);
  }

  public void setInt32_member(int value) {
    li_stdintJNI.StdInts_int32_member_set(swigCPtr, this, value);
  }

  public int getInt32_member() {
    return li_stdintJNI.StdInts_int32_member_get(swigCPtr, this);
  }

  public void setInt64_member(long value) {
    li_stdintJNI.StdInts_int64_member_set(swigCPtr, this, value);
  }

  public long getInt64_member() {
    return li_stdintJNI.StdInts_int64_member_get(swigCPtr, this);
  }

  public void setUint8_member(short value) {
    li_stdintJNI.StdInts_uint8_member_set(swigCPtr, this, value);
  }

  public short getUint8_member() {
    return li_stdintJNI.StdInts_uint8_member_get(swigCPtr, this);
  }

  public void setUint16_member(int value) {
    li_stdintJNI.StdInts_uint16_member_set(swigCPtr, this, value);
  }

  public int getUint16_member() {
    return li_stdintJNI.StdInts_uint16_member_get(swigCPtr, this);
  }

  public void setUint32_member(long value) {
    li_stdintJNI.StdInts_uint32_member_set(swigCPtr, this, value);
  }

  public long getUint32_member() {
    return li_stdintJNI.StdInts_uint32_member_get(swigCPtr, this);
  }

  public void setUint64_member(java.math.BigInteger value) {
    li_stdintJNI.StdInts_uint64_member_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getUint64_member() {
    return li_stdintJNI.StdInts_uint64_member_get(swigCPtr, this);
  }

  public StdInts() {
    this(li_stdintJNI.new_StdInts(), true);
  }

}
