/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package contract;

public class C extends A {
  private long swigCPtr;

  protected C(long cPtr, boolean cMemoryOwn) {
    super(contractJNI.C_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(C obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        contractJNI.delete_C(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int foo(int a, int b, int c, int d, int e) {
    return contractJNI.C_foo(swigCPtr, this, a, b, c, d, e);
  }

  public int bar(int a, int b, int c, int d, int e) {
    return contractJNI.C_bar(swigCPtr, this, a, b, c, d, e);
  }

  public C() {
    this(contractJNI.new_C(), true);
  }

}
