/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package li_boost_shared_ptr_template;

public class li_boost_shared_ptr_templateJNI {
  public final static native int bar_getter(long jarg1, BaseINTEGER jarg1_);
  public final static native int BaseINTEGER_bar(long jarg1, BaseINTEGER jarg1_);
  public final static native long new_BaseINTEGER();
  public final static native void delete_BaseINTEGER(long jarg1);
  public final static native int DerivedINTEGER_bar(long jarg1, DerivedINTEGER jarg1_);
  public final static native long new_DerivedINTEGER();
  public final static native void delete_DerivedINTEGER(long jarg1);
  public final static native int bar2_getter(long jarg1, BaseDefaultInt jarg1_);
  public final static native int BaseDefaultInt_bar2(long jarg1, BaseDefaultInt jarg1_);
  public final static native long new_BaseDefaultInt();
  public final static native void delete_BaseDefaultInt(long jarg1);
  public final static native int DerivedDefaultInt_bar2(long jarg1, DerivedDefaultInt jarg1_);
  public final static native long new_DerivedDefaultInt();
  public final static native void delete_DerivedDefaultInt(long jarg1);
  public final static native int DerivedDefaultInt2_bar2(long jarg1, DerivedDefaultInt2 jarg1_);
  public final static native long new_DerivedDefaultInt2();
  public final static native void delete_DerivedDefaultInt2(long jarg1);
  public final static native long DerivedINTEGER_SWIGSmartPtrUpcast(long jarg1);
  public final static native long DerivedDefaultInt_SWIGSmartPtrUpcast(long jarg1);
  public final static native long DerivedDefaultInt2_SWIGSmartPtrUpcast(long jarg1);
}
