/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package typedef_array_member;

public class typedef_array_memberJNI {
  public final static native void Foo_x_set(long jarg1, Foo jarg1_, String jarg2);
  public final static native String Foo_x_get(long jarg1, Foo jarg1_);
  public final static native long new_Foo();
  public final static native void delete_Foo(long jarg1);
  public final static native void Ast_channel_jmp_set(long jarg1, Ast_channel jarg1_, long jarg2);
  public final static native long Ast_channel_jmp_get(long jarg1, Ast_channel jarg1_);
  public final static native long new_Ast_channel();
  public final static native void delete_Ast_channel(long jarg1);
}
