/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package immutable_values;

public class immutable_valuesJNI {
  public final static native int ABC_get();
  public final static native int XYZ_get();
  public final static native int Tre_get();
  public final static native int Duo_get();
  public final static native int Uno_get();
}
