/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package immutable_values;

public interface immutable_valuesConstants {
  public final static int ABC = immutable_valuesJNI.ABC_get();
  public final static int XYZ = immutable_valuesJNI.XYZ_get();
}
