/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_DIRECTOR_PRIMITIVES_WRAP_H_
#define SWIG_DIRECTOR_PRIMITIVES_WRAP_H_

class SwigDirector_Base : public Base, public Swig::Director {

public:
    SwigDirector_Base(zval *self, double dd TSRMLS_DC);
    virtual ~SwigDirector_Base();
    virtual void NoParmsMethod();
    virtual bool BoolMethod(bool x);
    virtual int IntMethod(int x);
    virtual unsigned int UIntMethod(unsigned int x);
    virtual float FloatMethod(float x);
    virtual char *CharPtrMethod(char *x);
    virtual char const *ConstCharPtrMethod(char const *x);
    virtual HShadowMode EnumMethod(HShadowMode x);
    virtual void ManyParmsMethod(bool b, int i, unsigned int u, float f, char *c, char const *cc, HShadowMode h);
    virtual void NotOverriddenMethod();
};
class SwigDirector_Derived : public Derived, public Swig::Director {

public:
    SwigDirector_Derived(zval *self, double dd TSRMLS_DC);
    virtual ~SwigDirector_Derived();
    virtual void NoParmsMethod();
    virtual bool BoolMethod(bool x);
    virtual int IntMethod(int x);
    virtual unsigned int UIntMethod(unsigned int x);
    virtual float FloatMethod(float x);
    virtual char *CharPtrMethod(char *x);
    virtual char const *ConstCharPtrMethod(char const *x);
    virtual HShadowMode EnumMethod(HShadowMode x);
    virtual void ManyParmsMethod(bool b, int i, unsigned int u, float f, char *c, char const *cc, HShadowMode h);
    virtual void NotOverriddenMethod();
};

#endif
