<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('namespace_virtual_method')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_namespace_virtual_method.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('namespace_virtual_method.so')) return;
    } else {
      if (!dl('namespace_virtual_method.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



/* PHP Proxy Classes */
abstract class Foo {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_namespace_virtual_method_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_namespace_virtual_method_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}
	function __construct($h) {
		$this->_cPtr=$h;
	}

	function bar($x) {
		return Foo_bar($this->_cPtr,$x);
	}
}

class Spam extends Foo {
	public $_cPtr=null;

	function __set($var,$value) {
		if ($var === 'thisown') return swig_namespace_virtual_method_alter_newobject($this->_cPtr,$value);
		Foo::__set($var,$value);
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return Foo::__isset($var);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_namespace_virtual_method_get_newobject($this->_cPtr);
		return Foo::__get($var);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_A__C__Spam') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_Spam();
	}

	function bar($x) {
		return Spam_bar($this->_cPtr,$x);
	}
}


?>
