/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_TEMPLATE_ENUM_H
#define PHP_TEMPLATE_ENUM_H

extern zend_module_entry template_enum_module_entry;
#define phpext_template_enum_ptr &template_enum_module_entry

#ifdef PHP_WIN32
# define PHP_TEMPLATE_ENUM_API __declspec(dllexport)
#else
# define PHP_TEMPLATE_ENUM_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(template_enum);
PHP_MSHUTDOWN_FUNCTION(template_enum);
PHP_RINIT_FUNCTION(template_enum);
PHP_RSHUTDOWN_FUNCTION(template_enum);
PHP_MINFO_FUNCTION(template_enum);

ZEND_NAMED_FUNCTION(_wrap_new_foo_i);
ZEND_NAMED_FUNCTION(_wrap_new_foo_d);
ZEND_NAMED_FUNCTION(_wrap_new_RGBTraits);
ZEND_NAMED_FUNCTION(_wrap_Color_data_set);
ZEND_NAMED_FUNCTION(_wrap_Color_data_get);
ZEND_NAMED_FUNCTION(_wrap_new_Color);
#endif /* PHP_TEMPLATE_ENUM_H */
