/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_LEXTYPE_H
#define PHP_LEXTYPE_H

extern zend_module_entry lextype_module_entry;
#define phpext_lextype_ptr &lextype_module_entry

#ifdef PHP_WIN32
# define PHP_LEXTYPE_API __declspec(dllexport)
#else
# define PHP_LEXTYPE_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(lextype);
PHP_MSHUTDOWN_FUNCTION(lextype);
PHP_RINIT_FUNCTION(lextype);
PHP_RSHUTDOWN_FUNCTION(lextype);
PHP_MINFO_FUNCTION(lextype);

ZEND_NAMED_FUNCTION(_wrap_eat);
ZEND_NAMED_FUNCTION(_wrap_drink);
ZEND_NAMED_FUNCTION(_wrap_mate);
#endif /* PHP_LEXTYPE_H */
