/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_CONVERSION_NS_TEMPLATE_H
#define PHP_CONVERSION_NS_TEMPLATE_H

extern zend_module_entry conversion_ns_template_module_entry;
#define phpext_conversion_ns_template_ptr &conversion_ns_template_module_entry

#ifdef PHP_WIN32
# define PHP_CONVERSION_NS_TEMPLATE_API __declspec(dllexport)
#else
# define PHP_CONVERSION_NS_TEMPLATE_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(conversion_ns_template);
PHP_MSHUTDOWN_FUNCTION(conversion_ns_template);
PHP_RINIT_FUNCTION(conversion_ns_template);
PHP_RSHUTDOWN_FUNCTION(conversion_ns_template);
PHP_MINFO_FUNCTION(conversion_ns_template);

ZEND_NAMED_FUNCTION(_wrap_new_create);
ZEND_NAMED_FUNCTION(_wrap_new_Foo_One);
ZEND_NAMED_FUNCTION(_wrap_new_Bar_create);
ZEND_NAMED_FUNCTION(_wrap_Bar_One_hello1);
ZEND_NAMED_FUNCTION(_wrap_Bar_One_hello2);
#endif /* PHP_CONVERSION_NS_TEMPLATE_H */
