/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_IMPORT_STL_A_H
#define PHP_IMPORT_STL_A_H

extern zend_module_entry import_stl_a_module_entry;
#define phpext_import_stl_a_ptr &import_stl_a_module_entry

#ifdef PHP_WIN32
# define PHP_IMPORT_STL_A_API __declspec(dllexport)
#else
# define PHP_IMPORT_STL_A_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(import_stl_a);
PHP_MSHUTDOWN_FUNCTION(import_stl_a);
PHP_RINIT_FUNCTION(import_stl_a);
PHP_RSHUTDOWN_FUNCTION(import_stl_a);
PHP_MINFO_FUNCTION(import_stl_a);

ZEND_NAMED_FUNCTION(_wrap_new_VectorInt);
ZEND_NAMED_FUNCTION(_wrap_VectorInt_size);
ZEND_NAMED_FUNCTION(_wrap_VectorInt_capacity);
ZEND_NAMED_FUNCTION(_wrap_VectorInt_reserve);
ZEND_NAMED_FUNCTION(_wrap_VectorInt_clear);
ZEND_NAMED_FUNCTION(_wrap_VectorInt_push);
ZEND_NAMED_FUNCTION(_wrap_VectorInt_is_empty);
ZEND_NAMED_FUNCTION(_wrap_VectorInt_pop);
ZEND_NAMED_FUNCTION(_wrap_VectorInt_get);
ZEND_NAMED_FUNCTION(_wrap_VectorInt_set);
#endif /* PHP_IMPORT_STL_A_H */
