/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_TYPEMAP_GLOBAL_SCOPE_H
#define PHP_TYPEMAP_GLOBAL_SCOPE_H

extern zend_module_entry typemap_global_scope_module_entry;
#define phpext_typemap_global_scope_ptr &typemap_global_scope_module_entry

#ifdef PHP_WIN32
# define PHP_TYPEMAP_GLOBAL_SCOPE_API __declspec(dllexport)
#else
# define PHP_TYPEMAP_GLOBAL_SCOPE_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(typemap_global_scope);
PHP_MSHUTDOWN_FUNCTION(typemap_global_scope);
PHP_RINIT_FUNCTION(typemap_global_scope);
PHP_RSHUTDOWN_FUNCTION(typemap_global_scope);
PHP_MINFO_FUNCTION(typemap_global_scope);

ZEND_NAMED_FUNCTION(_wrap_new_Test1);
ZEND_NAMED_FUNCTION(_wrap_new_Test2);
ZEND_NAMED_FUNCTION(_wrap_new_Test3);
ZEND_NAMED_FUNCTION(_wrap_new_Test4);
ZEND_NAMED_FUNCTION(_wrap_test1a);
ZEND_NAMED_FUNCTION(_wrap_test1b);
ZEND_NAMED_FUNCTION(_wrap_test2a);
ZEND_NAMED_FUNCTION(_wrap_test2b);
ZEND_NAMED_FUNCTION(_wrap_test3a);
ZEND_NAMED_FUNCTION(_wrap_test3b);
ZEND_NAMED_FUNCTION(_wrap_test3c);
ZEND_NAMED_FUNCTION(_wrap_test3d);
ZEND_NAMED_FUNCTION(_wrap_test3e);
ZEND_NAMED_FUNCTION(_wrap_test4a);
ZEND_NAMED_FUNCTION(_wrap_test4b);
ZEND_NAMED_FUNCTION(_wrap_test4c);
ZEND_NAMED_FUNCTION(_wrap_test4d);
ZEND_NAMED_FUNCTION(_wrap_test4e);
ZEND_NAMED_FUNCTION(_wrap_new_XX);
ZEND_NAMED_FUNCTION(_wrap_TemplateTest1XX_m_t_set);
ZEND_NAMED_FUNCTION(_wrap_TemplateTest1XX_m_t_get);
ZEND_NAMED_FUNCTION(_wrap_new_TemplateTest1XX);
ZEND_NAMED_FUNCTION(_wrap_TemplateTest2XX_m_t_set);
ZEND_NAMED_FUNCTION(_wrap_TemplateTest2XX_m_t_get);
ZEND_NAMED_FUNCTION(_wrap_new_TemplateTest2XX);
ZEND_NAMED_FUNCTION(_wrap_TemplateTest3XX_m_t_set);
ZEND_NAMED_FUNCTION(_wrap_TemplateTest3XX_m_t_get);
ZEND_NAMED_FUNCTION(_wrap_new_TemplateTest3XX);
ZEND_NAMED_FUNCTION(_wrap_TemplateTest4XX_m_t_set);
ZEND_NAMED_FUNCTION(_wrap_TemplateTest4XX_m_t_get);
ZEND_NAMED_FUNCTION(_wrap_new_TemplateTest4XX);
ZEND_NAMED_FUNCTION(_wrap_test_template_1a);
ZEND_NAMED_FUNCTION(_wrap_test_template_1b);
ZEND_NAMED_FUNCTION(_wrap_test_template_2a);
ZEND_NAMED_FUNCTION(_wrap_test_template_2b);
ZEND_NAMED_FUNCTION(_wrap_test_template_3a);
ZEND_NAMED_FUNCTION(_wrap_test_template_3b);
ZEND_NAMED_FUNCTION(_wrap_test_template_3c);
ZEND_NAMED_FUNCTION(_wrap_test_template_3d);
ZEND_NAMED_FUNCTION(_wrap_test_template_3e);
ZEND_NAMED_FUNCTION(_wrap_test_template_4a);
ZEND_NAMED_FUNCTION(_wrap_test_template_4b);
ZEND_NAMED_FUNCTION(_wrap_test_template_4c);
ZEND_NAMED_FUNCTION(_wrap_test_template_4d);
ZEND_NAMED_FUNCTION(_wrap_test_template_4e);
ZEND_NAMED_FUNCTION(_wrap_test_enum_1a);
ZEND_NAMED_FUNCTION(_wrap_test_enum_1b);
ZEND_NAMED_FUNCTION(_wrap_test_enum_2a);
ZEND_NAMED_FUNCTION(_wrap_test_enum_2b);
ZEND_NAMED_FUNCTION(_wrap_test_enum_3a);
ZEND_NAMED_FUNCTION(_wrap_test_enum_3b);
ZEND_NAMED_FUNCTION(_wrap_test_enum_3c);
ZEND_NAMED_FUNCTION(_wrap_test_enum_3d);
ZEND_NAMED_FUNCTION(_wrap_test_enum_3e);
ZEND_NAMED_FUNCTION(_wrap_test_enum_4a);
ZEND_NAMED_FUNCTION(_wrap_test_enum_4b);
ZEND_NAMED_FUNCTION(_wrap_test_enum_4c);
ZEND_NAMED_FUNCTION(_wrap_test_enum_4d);
ZEND_NAMED_FUNCTION(_wrap_test_enum_4e);
#endif /* PHP_TYPEMAP_GLOBAL_SCOPE_H */
