<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('template_default_inherit')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_template_default_inherit.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('template_default_inherit.so')) return;
    } else {
      if (!dl('template_default_inherit.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



/* PHP Proxy Classes */
class A_int {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_template_default_inherit_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_template_default_inherit_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	const nindex = A_int_nindex;

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_AT_int_t') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_A_int();
	}
}

class B_int extends A_int {
	public $_cPtr=null;

	function __set($var,$value) {
		if ($var === 'thisown') return swig_template_default_inherit_alter_newobject($this->_cPtr,$value);
		A_int::__set($var,$value);
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return A_int::__isset($var);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_template_default_inherit_get_newobject($this->_cPtr);
		return A_int::__get($var);
	}

	function say_hi($index=null) {
		switch (func_num_args()) {
		case 0: B_int_say_hi($this->_cPtr); break;
		default: B_int_say_hi($this->_cPtr,$index);
		}
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_BT_int_t') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_B_int();
	}
}


?>
