<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('template_typedef_import')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_template_typedef_import.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('template_typedef_import.so')) return;
    } else {
      if (!dl('template_typedef_import.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class template_typedef_import {
	static function my_func_r($hello) {
		return my_func_r($hello);
	}

	static function my_func_c($hello) {
		return my_func_c($hello);
	}
}

/* PHP Proxy Classes */
class Sin extends ArithUnaryFunction_double_double {
	public $_cPtr=null;

	function __set($var,$value) {
		if ($var === 'thisown') return swig_template_typedef_import_alter_newobject($this->_cPtr,$value);
		ArithUnaryFunction_double_double::__set($var,$value);
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return ArithUnaryFunction_double_double::__isset($var);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_template_typedef_import_get_newobject($this->_cPtr);
		return ArithUnaryFunction_double_double::__get($var);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_Sin') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_Sin();
	}
}

class CSin extends ArithUnaryFunction_complex_complex {
	public $_cPtr=null;

	function __set($var,$value) {
		if ($var === 'thisown') return swig_template_typedef_import_alter_newobject($this->_cPtr,$value);
		ArithUnaryFunction_complex_complex::__set($var,$value);
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return ArithUnaryFunction_complex_complex::__isset($var);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_template_typedef_import_get_newobject($this->_cPtr);
		return ArithUnaryFunction_complex_complex::__get($var);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CSin') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CSin();
	}
}


?>
