<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('template_typemaps')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_template_typemaps.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('template_typemaps.so')) return;
    } else {
      if (!dl('template_typemaps.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class template_typemaps {
	static function bar($foo) {
		return bar($foo);
	}
}

/* PHP Proxy Classes */
class Foo_I1 {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'val') return Foo_I1_val_set($this->_cPtr,$value);
		if ($var === 'thisown') return swig_template_typemaps_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if (function_exists('Foo_I1_'.$var.'_set')) return true;
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'val') return Foo_I1_val_get($this->_cPtr);
		if ($var === 'thisown') return swig_template_typemaps_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function get_value() {
		return Foo_I1_get_value($this->_cPtr);
	}

	function set_value($v) {
		Foo_I1_set_value($this->_cPtr,$v);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_FooT_Integer1_t') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_Foo_I1();
	}
}

class Foo_I2 {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'val') return Foo_I2_val_set($this->_cPtr,$value);
		if ($var === 'thisown') return swig_template_typemaps_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if (function_exists('Foo_I2_'.$var.'_set')) return true;
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'val') return Foo_I2_val_get($this->_cPtr);
		if ($var === 'thisown') return swig_template_typemaps_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function get_value() {
		return Foo_I2_get_value($this->_cPtr);
	}

	function set_value($v) {
		Foo_I2_set_value($this->_cPtr,$v);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_FooT_int_t') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_Foo_I2();
	}
}


?>
