<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('template_typedef')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_template_typedef.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('template_typedef.so')) return;
    } else {
      if (!dl('template_typedef.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class template_typedef {
	static function make_Identity_float() {
		$r=make_Identity_float();
		if (is_resource($r)) {
			$c=substr(get_resource_type($r), (strpos(get_resource_type($r), '__') ? strpos(get_resource_type($r), '__') + 2 : 3));
			if (class_exists($c)) return new $c($r);
			return new ArithUnaryFunction_float_float($r);
		}
		return $r;
	}

	static function make_Identity_reald() {
		$r=make_Identity_reald();
		if (is_resource($r)) {
			$c=substr(get_resource_type($r), (strpos(get_resource_type($r), '__') ? strpos(get_resource_type($r), '__') + 2 : 3));
			if (class_exists($c)) return new $c($r);
			return new ArithUnaryFunction_reald_reald($r);
		}
		return $r;
	}

	static function make_Multiplies_float_float_reald_reald($f,$g) {
		$r=make_Multiplies_float_float_reald_reald($f,$g);
		if (is_resource($r)) {
			$c=substr(get_resource_type($r), (strpos(get_resource_type($r), '__') ? strpos(get_resource_type($r), '__') + 2 : 3));
			if (class_exists($c)) return new $c($r);
			return new ArithUnaryFunction_float_reald($r);
		}
		return $r;
	}

	static function make_Multiplies_float_float_float_float($f,$g) {
		$r=make_Multiplies_float_float_float_float($f,$g);
		if (is_resource($r)) {
			$c=substr(get_resource_type($r), (strpos(get_resource_type($r), '__') ? strpos(get_resource_type($r), '__') + 2 : 3));
			if (class_exists($c)) return new $c($r);
			return new ArithUnaryFunction_float_float($r);
		}
		return $r;
	}

	static function make_Multiplies_reald_reald_reald_reald($f,$g) {
		$r=make_Multiplies_reald_reald_reald_reald($f,$g);
		if (is_resource($r)) {
			$c=substr(get_resource_type($r), (strpos(get_resource_type($r), '__') ? strpos(get_resource_type($r), '__') + 2 : 3));
			if (class_exists($c)) return new $c($r);
			return new ArithUnaryFunction_reald_reald($r);
		}
		return $r;
	}
}

/* PHP Proxy Classes */
class UnaryFunctionBase {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_template_typedef_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_template_typedef_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_vfncs__UnaryFunctionBase') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_UnaryFunctionBase();
	}
}

class UnaryFunction_float_float extends UnaryFunctionBase {
	public $_cPtr=null;

	function __set($var,$value) {
		if ($var === 'thisown') return swig_template_typedef_alter_newobject($this->_cPtr,$value);
		UnaryFunctionBase::__set($var,$value);
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return UnaryFunctionBase::__isset($var);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_template_typedef_get_newobject($this->_cPtr);
		return UnaryFunctionBase::__get($var);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_vfncs__UnaryFunctionT_float_float_t') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_UnaryFunction_float_float();
	}
}

class ArithUnaryFunction_float_float extends UnaryFunction_float_float {
	public $_cPtr=null;

	function __set($var,$value) {
		if ($var === 'thisown') return swig_template_typedef_alter_newobject($this->_cPtr,$value);
		UnaryFunction_float_float::__set($var,$value);
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return UnaryFunction_float_float::__isset($var);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_template_typedef_get_newobject($this->_cPtr);
		return UnaryFunction_float_float::__get($var);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_vfncs__ArithUnaryFunctionT_float_float_t') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_ArithUnaryFunction_float_float();
	}
}

class UnaryFunction_reald_reald extends UnaryFunctionBase {
	public $_cPtr=null;

	function __set($var,$value) {
		if ($var === 'thisown') return swig_template_typedef_alter_newobject($this->_cPtr,$value);
		UnaryFunctionBase::__set($var,$value);
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return UnaryFunctionBase::__isset($var);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_template_typedef_get_newobject($this->_cPtr);
		return UnaryFunctionBase::__get($var);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_vfncs__UnaryFunctionT_double_double_t') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_UnaryFunction_reald_reald();
	}
}

class ArithUnaryFunction_reald_reald extends UnaryFunction_reald_reald {
	public $_cPtr=null;

	function __set($var,$value) {
		if ($var === 'thisown') return swig_template_typedef_alter_newobject($this->_cPtr,$value);
		UnaryFunction_reald_reald::__set($var,$value);
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return UnaryFunction_reald_reald::__isset($var);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_template_typedef_get_newobject($this->_cPtr);
		return UnaryFunction_reald_reald::__get($var);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_vfncs__ArithUnaryFunctionT_double_double_t') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_ArithUnaryFunction_reald_reald();
	}
}

class UnaryFunction_float_reald extends UnaryFunctionBase {
	public $_cPtr=null;

	function __set($var,$value) {
		if ($var === 'thisown') return swig_template_typedef_alter_newobject($this->_cPtr,$value);
		UnaryFunctionBase::__set($var,$value);
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return UnaryFunctionBase::__isset($var);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_template_typedef_get_newobject($this->_cPtr);
		return UnaryFunctionBase::__get($var);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_vfncs__UnaryFunctionT_float_double_t') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_UnaryFunction_float_reald();
	}
}

class ArithUnaryFunction_float_reald extends UnaryFunction_float_reald {
	public $_cPtr=null;

	function __set($var,$value) {
		if ($var === 'thisown') return swig_template_typedef_alter_newobject($this->_cPtr,$value);
		UnaryFunction_float_reald::__set($var,$value);
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return UnaryFunction_float_reald::__isset($var);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_template_typedef_get_newobject($this->_cPtr);
		return UnaryFunction_float_reald::__get($var);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_vfncs__ArithUnaryFunctionT_float_double_t') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_ArithUnaryFunction_float_reald();
	}
}


?>
