<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('using_directive_and_declaration_forward')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_using_directive_and_declaration_forward.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('using_directive_and_declaration_forward.so')) return;
    } else {
      if (!dl('using_directive_and_declaration_forward.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class using_directive_and_declaration_forward {
	static function useit1($t) {
		useit1($t);
	}

	static function useit1a($t) {
		useit1a($t);
	}

	static function useit1b($t) {
		useit1b($t);
	}

	static function useit1c($t) {
		useit1c($t);
	}

	static function useit2($t) {
		useit2($t);
	}

	static function useit2a($t) {
		useit2a($t);
	}

	static function useit2b($t) {
		useit2b($t);
	}

	static function useit2c($t) {
		useit2c($t);
	}

	static function useit2d($t) {
		useit2d($t);
	}

	static function useit3($t) {
		useit3($t);
	}

	static function useit3a($t) {
		useit3a($t);
	}

	static function useit3b($t) {
		useit3b($t);
	}

	static function useit3c($t) {
		useit3c($t);
	}

	static function useit3d($t) {
		useit3d($t);
	}

	static function useit4($t) {
		useit4($t);
	}

	static function useit4a($t) {
		useit4a($t);
	}

	static function useit4b($t) {
		useit4b($t);
	}

	static function useit4c($t) {
		useit4c($t);
	}

	static function useit4d($t) {
		useit4d($t);
	}

	static function useit5($t) {
		useit5($t);
	}

	static function useit5a($t) {
		useit5a($t);
	}

	static function useit5b($t) {
		useit5b($t);
	}

	static function useit5c($t) {
		useit5c($t);
	}

	static function useit5d($t) {
		useit5d($t);
	}

	static function useit7($t) {
		useit7($t);
	}

	static function useit7a($t) {
		useit7a($t);
	}

	static function useit7b($t) {
		useit7b($t);
	}

	static function useit7c($t) {
		useit7c($t);
	}

	static function useit7d($t) {
		useit7d($t);
	}
}

/* PHP Proxy Classes */
class Thing1 {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_using_directive_and_declaration_forward_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_using_directive_and_declaration_forward_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_Outer1__Space1__Thing1') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_Thing1();
	}
}

class Thing2 {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_using_directive_and_declaration_forward_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_using_directive_and_declaration_forward_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_Outer2__Space2__Thing2') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_Thing2();
	}
}

class Thing3 {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_using_directive_and_declaration_forward_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_using_directive_and_declaration_forward_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_Outer3__Space3__Middle3__Thing3') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_Thing3();
	}
}

class Thing4 {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_using_directive_and_declaration_forward_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_using_directive_and_declaration_forward_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_Outer4__Space4__Middle4__Thing4') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_Thing4();
	}
}

class Thing5 {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_using_directive_and_declaration_forward_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_using_directive_and_declaration_forward_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_Outer5__Space5__Middle5__More5__Thing5') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_Thing5();
	}
}

class Thing7 {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_using_directive_and_declaration_forward_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_using_directive_and_declaration_forward_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_Outer7__Space7__Middle7__Thing7') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_Thing7();
	}
}


?>
