/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cpp_enum;

public final class SOME_ENUM {
  public final static SOME_ENUM ENUM_ONE = new SOME_ENUM("ENUM_ONE");
  public final static SOME_ENUM ENUM_TWO = new SOME_ENUM("ENUM_TWO");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SOME_ENUM swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SOME_ENUM.class + " with value " + swigValue);
  }

  private SOME_ENUM(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SOME_ENUM(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SOME_ENUM(String swigName, SOME_ENUM swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SOME_ENUM[] swigValues = { ENUM_ONE, ENUM_TWO };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

