/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package template_typemaps;

public class template_typemapsJNI {
  public final static native void Foo_I1_val_set(long jarg1, Foo_I1 jarg1_, long jarg2);
  public final static native long Foo_I1_val_get(long jarg1, Foo_I1 jarg1_);
  public final static native long Foo_I1_get_value(long jarg1, Foo_I1 jarg1_);
  public final static native void Foo_I1_set_value(long jarg1, Foo_I1 jarg1_, long jarg2);
  public final static native long new_Foo_I1();
  public final static native void delete_Foo_I1(long jarg1);
  public final static native void Foo_I2_val_set(long jarg1, Foo_I2 jarg1_, int jarg2);
  public final static native int Foo_I2_val_get(long jarg1, Foo_I2 jarg1_);
  public final static native int Foo_I2_get_value(long jarg1, Foo_I2 jarg1_);
  public final static native void Foo_I2_set_value(long jarg1, Foo_I2 jarg1_, int jarg2);
  public final static native long new_Foo_I2();
  public final static native void delete_Foo_I2(long jarg1);
  public final static native int bar(long jarg1, Foo_I1 jarg1_);
}
