/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package template_default_inherit;

public class template_default_inheritJNI {
  public final static native long A_int_nindex_get();
  public final static native long new_A_int();
  public final static native void delete_A_int(long jarg1);
  public final static native void B_int_say_hi__SWIG_0(long jarg1, B_int jarg1_, long jarg2);
  public final static native void B_int_say_hi__SWIG_1(long jarg1, B_int jarg1_);
  public final static native long new_B_int();
  public final static native void delete_B_int(long jarg1);
  public final static native long B_int_SWIGUpcast(long jarg1);
}
