/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package template_default_arg;

public class Y_unsigned {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Y_unsigned(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Y_unsigned obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        template_default_argJNI.delete_Y_unsigned(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long meth(double a, long t) {
    return template_default_argJNI.Y_unsigned_meth_SWIG_0_0(swigCPtr, this, a, t);
  }

  public long meth(double a) {
    return template_default_argJNI.Y_unsigned_meth_SWIG_0_1(swigCPtr, this, a);
  }

  public long meth(long t) {
    return template_default_argJNI.Y_unsigned_meth_SWIG_0_2(swigCPtr, this, t);
  }

  public long meth() {
    return template_default_argJNI.Y_unsigned_meth_SWIG_0_3(swigCPtr, this);
  }

  public Y_unsigned() {
    this(template_default_argJNI.new_Y_unsigned(), true);
  }

}
