/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package li_boost_shared_ptr;

public class KlassDerived extends Klass {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected KlassDerived(long cPtr, boolean cMemoryOwn) {
    super(li_boost_shared_ptrJNI.KlassDerived_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KlassDerived obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        li_boost_shared_ptrJNI.delete_KlassDerived(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public KlassDerived() {
    this(li_boost_shared_ptrJNI.new_KlassDerived__SWIG_0(), true);
  }

  public KlassDerived(String val) {
    this(li_boost_shared_ptrJNI.new_KlassDerived__SWIG_1(val), true);
  }

  public KlassDerived(KlassDerived other) {
    this(li_boost_shared_ptrJNI.new_KlassDerived__SWIG_2(KlassDerived.getCPtr(other), other), true);
  }

  public String getValue() {
    return li_boost_shared_ptrJNI.KlassDerived_getValue(swigCPtr, this);
  }

}
