/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package smart_pointer_extend;

public class CBase {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        smart_pointer_extendJNI.delete_CBase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static int hello() {
    return smart_pointer_extendJNI.CBase_hello();
  }

  public void setX(int value) {
    smart_pointer_extendJNI.CBase_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return smart_pointer_extendJNI.CBase_x_get(swigCPtr, this);
  }

  public int foo() {
    return smart_pointer_extendJNI.CBase_foo(swigCPtr, this);
  }

  public int bar() {
    return smart_pointer_extendJNI.CBase_bar(swigCPtr, this);
  }

  public int boo(int i) {
    return smart_pointer_extendJNI.CBase_boo(swigCPtr, this, i);
  }

  public CBase() {
    this(smart_pointer_extendJNI.new_CBase(), true);
  }

  public final static int z = smart_pointer_extendJNI.CBase_z_get();
}
