/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package template_typedef_ptr;

public class template_typedef_ptrJNI {
  public final static native long new_C();
  public final static native void delete_C(long jarg1);
  public final static native long new_test_pC(long jarg1, C jarg1_);
  public final static native void delete_test_pC(long jarg1);
}
