/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package li_std_except_as_class;

public class li_std_except_as_class {
  public static void test_domain_error() {
    li_std_except_as_classJNI.test_domain_error();
  }

}
