/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package inherit_target_language;

public class inherit_target_languageJNI {
  public final static native void delete_Base2(long jarg1);
  public final static native long new_Base2();
  public final static native long new_Derived1();
  public final static native void delete_Derived1(long jarg1);
  public final static native long new_Derived2();
  public final static native void delete_Derived2(long jarg1);
  public final static native void delete_MBase2a(long jarg1);
  public final static native void MBase2a_c(long jarg1, MBase2a jarg1_);
  public final static native long new_MBase2a();
  public final static native void delete_MBase2b(long jarg1);
  public final static native void MBase2b_d(long jarg1, MBase2b jarg1_);
  public final static native long new_MBase2b();
  public final static native long new_MultipleDerived1();
  public final static native void delete_MultipleDerived1(long jarg1);
  public final static native long new_MultipleDerived2();
  public final static native void delete_MultipleDerived2(long jarg1);
  public final static native void delete_MBase3b(long jarg1);
  public final static native void MBase3b_f(long jarg1, MBase3b jarg1_);
  public final static native long new_MBase3b();
  public final static native void delete_MBase4a(long jarg1);
  public final static native void MBase4a_g(long jarg1, MBase4a jarg1_);
  public final static native long new_MBase4a();
  public final static native long new_MultipleDerived3();
  public final static native void delete_MultipleDerived3(long jarg1);
  public final static native long new_MultipleDerived4();
  public final static native void delete_MultipleDerived4(long jarg1);
  public final static native void delete_BaseX(long jarg1);
  public final static native void BaseX_basex(long jarg1, BaseX jarg1_);
  public final static native long new_BaseX();
  public final static native void DerivedX_derivedx(long jarg1, DerivedX jarg1_);
  public final static native long new_DerivedX();
  public final static native void delete_DerivedX(long jarg1);
  public final static native long MultipleDerived3_SWIGUpcast(long jarg1);
  public final static native long MultipleDerived4_SWIGUpcast(long jarg1);
  public final static native long DerivedX_SWIGUpcast(long jarg1);
}
