/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package inherit_target_language;

public class MBase3b extends TargetLanguageBase {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MBase3b(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MBase3b obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        inherit_target_languageJNI.delete_MBase3b(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void f() {
    inherit_target_languageJNI.MBase3b_f(swigCPtr, this);
  }

  public MBase3b() {
    this(inherit_target_languageJNI.new_MBase3b(), true);
  }

}
