/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package enum_forward;

public class enum_forward {
  public static ForwardEnum1 get_enum1() {
    return ForwardEnum1.swigToEnum(enum_forwardJNI.get_enum1());
  }

  public static ForwardEnum1 test_function1(ForwardEnum1 e) {
    return ForwardEnum1.swigToEnum(enum_forwardJNI.test_function1(e.swigValue()));
  }

  public static ForwardEnum2 get_enum2() {
    return ForwardEnum2.swigToEnum(enum_forwardJNI.get_enum2());
  }

  public static ForwardEnum2 test_function2(ForwardEnum2 e) {
    return ForwardEnum2.swigToEnum(enum_forwardJNI.test_function2(e.swigValue()));
  }

  public static ForwardEnum3 get_enum3() {
    return ForwardEnum3.swigToEnum(enum_forwardJNI.get_enum3());
  }

  public static ForwardEnum3 test_function3(ForwardEnum3 e) {
    return ForwardEnum3.swigToEnum(enum_forwardJNI.test_function3(e.swigValue()));
  }

}
