/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package director_classes;

public class Caller {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Caller(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Caller obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        director_classesJNI.delete_Caller(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Caller() {
    this(director_classesJNI.new_Caller(), true);
  }

  public void set(Base b) {
    director_classesJNI.Caller_set(swigCPtr, this, Base.getCPtr(b), b);
  }

  public void reset() {
    director_classesJNI.Caller_reset(swigCPtr, this);
  }

  public DoubleHolder ValCall(DoubleHolder x) {
    return new DoubleHolder(director_classesJNI.Caller_ValCall(swigCPtr, this, DoubleHolder.getCPtr(x), x), true);
  }

  public DoubleHolder RefCall(DoubleHolder x) {
    return new DoubleHolder(director_classesJNI.Caller_RefCall(swigCPtr, this, DoubleHolder.getCPtr(x), x), false);
  }

  public DoubleHolder PtrCall(DoubleHolder x) {
    long cPtr = director_classesJNI.Caller_PtrCall(swigCPtr, this, DoubleHolder.getCPtr(x), x);
    return (cPtr == 0) ? null : new DoubleHolder(cPtr, false);
  }

  public String FullyOverloadedCall(int x) {
    return director_classesJNI.Caller_FullyOverloadedCall__SWIG_0(swigCPtr, this, x);
  }

  public String FullyOverloadedCall(boolean x) {
    return director_classesJNI.Caller_FullyOverloadedCall__SWIG_1(swigCPtr, this, x);
  }

  public String SemiOverloadedCall(int x) {
    return director_classesJNI.Caller_SemiOverloadedCall__SWIG_0(swigCPtr, this, x);
  }

  public String SemiOverloadedCall(boolean x) {
    return director_classesJNI.Caller_SemiOverloadedCall__SWIG_1(swigCPtr, this, x);
  }

  public String DefaultParmsCall(int x) {
    return director_classesJNI.Caller_DefaultParmsCall__SWIG_0(swigCPtr, this, x);
  }

  public String DefaultParmsCall(int x, double y) {
    return director_classesJNI.Caller_DefaultParmsCall__SWIG_1(swigCPtr, this, x, y);
  }

}
