/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package rename2;

public class XYZInt {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XYZInt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XYZInt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rename2JNI.delete_XYZInt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NotXYZInt opIntPtrA() {
    long cPtr = rename2JNI.XYZInt_opIntPtrA(swigCPtr, this);
    return (cPtr == 0) ? null : new NotXYZInt(cPtr, false);
  }

  public XYZInt opIntPtrB() {
    long cPtr = rename2JNI.XYZInt_opIntPtrB(swigCPtr, this);
    return (cPtr == 0) ? null : new XYZInt(cPtr, false);
  }

  public Another opAnother2() {
    return new Another(rename2JNI.XYZInt_opAnother2(swigCPtr, this), true);
  }

  public void tMethod2(int i) {
    rename2JNI.XYZInt_tMethod2(swigCPtr, this, i);
  }

  public void tMethodNotXYZ2(NotXYZInt i) {
    rename2JNI.XYZInt_tMethodNotXYZ2(swigCPtr, this, NotXYZInt.getCPtr(i), i);
  }

  public void tMethodXYZ2(XYZInt i) {
    rename2JNI.XYZInt_tMethodXYZ2(swigCPtr, this, XYZInt.getCPtr(i), i);
  }

  public int opT2() {
    return rename2JNI.XYZInt_opT2(swigCPtr, this);
  }

  public NotXYZInt opNotXYZ2() {
    return new NotXYZInt(rename2JNI.XYZInt_opNotXYZ2(swigCPtr, this), true);
  }

  public XYZInt opXYZ2() {
    return new XYZInt(rename2JNI.XYZInt_opXYZ2(swigCPtr, this), true);
  }

  public XYZInt() {
    this(rename2JNI.new_XYZInt(), true);
  }

}
