/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package abstract_signature;

public class abstract_bar extends abstract_foo {
  private long swigCPtr;

  protected abstract_bar(long cPtr, boolean cMemoryOwn) {
    super(abstract_signatureJNI.abstract_bar_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(abstract_bar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        abstract_signatureJNI.delete_abstract_bar(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int meth(int meth_param) {
    return abstract_signatureJNI.abstract_bar_meth__SWIG_0(swigCPtr, this, meth_param);
  }

  public int meth(int meth_param_1, int meth_param_2) {
    return abstract_signatureJNI.abstract_bar_meth__SWIG_1(swigCPtr, this, meth_param_1, meth_param_2);
  }

}
