/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package typedef_funcptr;

public class typedef_funcptrJNI {
  public final static native int do_op(int jarg1, int jarg2, long jarg3);
  public final static native long addf_get();
  public final static native long subf_get();
}
