/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package li_std_pair_using;

public class li_std_pair_using {
  public static StringStringPair bounce(StringStringPair p) {
    return new StringStringPair(li_std_pair_usingJNI.bounce(StringStringPair.getCPtr(p), p), true);
  }

}
