/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package li_boost_shared_ptr_bits;

public class NonDynamic {
  private long swigCPtr;
  private boolean swigCMemOwn;

  protected NonDynamic(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NonDynamic obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        li_boost_shared_ptr_bitsJNI.delete_NonDynamic(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setI(int value) {
    li_boost_shared_ptr_bitsJNI.NonDynamic_i_set(swigCPtr, this, value);
  }

  public int getI() {
    return li_boost_shared_ptr_bitsJNI.NonDynamic_i_get(swigCPtr, this);
  }

  public NonDynamic() {
    this(li_boost_shared_ptr_bitsJNI.new_NonDynamic(), true);
  }

}
