/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package friends;

public class friendsJNI {
  public final static native void globalscope();
  public final static native long new_B(int jarg1);
  public final static native int mix(long jarg1, A jarg1_, long jarg2, B jarg2_);
  public final static native void delete_B(long jarg1);
  public final static native long new_A(int jarg1);
  public final static native int get_val1__SWIG_0(long jarg1, A jarg1_);
  public final static native int get_val1__SWIG_1(long jarg1, A jarg1_, int jarg2);
  public final static native int get_val2(long jarg1, A jarg1_);
  public final static native int get_val3(long jarg1, A jarg1_);
  public final static native void delete_A(long jarg1);
  public final static native int get_val1__SWIG_2(int jarg1, int jarg2, int jarg3);
  public final static native void bas();
  public final static native void baz();
  public final static native long new_Foo();
  public final static native void Foo_member(long jarg1, Foo jarg1_);
  public final static native void delete_Foo(long jarg1);
  public final static native void bar();
  public final static native long new_D_i(int jarg1);
  public final static native int get_val1__SWIG_4(long jarg1, D_i jarg1_);
  public final static native void set__SWIG_1(long jarg1, D_i jarg1_, int jarg2);
  public final static native void delete_D_i(long jarg1);
  public final static native long new_D_d(double jarg1);
  public final static native double get_val1__SWIG_5(long jarg1, D_d jarg1_);
  public final static native void set__SWIG_2(long jarg1, D_d jarg1_, double jarg2);
  public final static native void delete_D_d(long jarg1);
}
