/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package special_variables;

public class DirectorTest {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DirectorTest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DirectorTest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        special_variablesJNI.delete_DirectorTest(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    special_variablesJNI.DirectorTest_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    special_variablesJNI.DirectorTest_change_ownership(this, swigCPtr, true);
  }

  public void director_testmethod(int i) {
    if (getClass() == DirectorTest.class) special_variablesJNI.DirectorTest_director_testmethod(swigCPtr, this, i); else special_variablesJNI.DirectorTest_director_testmethodSwigExplicitDirectorTest(swigCPtr, this, i);
  }

  public DirectorTest() {
    this(special_variablesJNI.new_DirectorTest(), true);
    special_variablesJNI.DirectorTest_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
