/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package director_basic;

public class Foo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Foo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Foo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        director_basicJNI.delete_Foo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    director_basicJNI.Foo_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    director_basicJNI.Foo_change_ownership(this, swigCPtr, true);
  }

  public String ping() {
    return (getClass() == Foo.class) ? director_basicJNI.Foo_ping(swigCPtr, this) : director_basicJNI.Foo_pingSwigExplicitFoo(swigCPtr, this);
  }

  public String pong() {
    return (getClass() == Foo.class) ? director_basicJNI.Foo_pong(swigCPtr, this) : director_basicJNI.Foo_pongSwigExplicitFoo(swigCPtr, this);
  }

  public static Foo get_self(Foo slf) {
    long cPtr = director_basicJNI.Foo_get_self(Foo.getCPtr(slf), slf);
    return (cPtr == 0) ? null : new Foo(cPtr, false);
  }

  public Foo() {
    this(director_basicJNI.new_Foo(), true);
    director_basicJNI.Foo_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
