/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class example {
  public static int gcd(int x, int y) {
    return exampleJNI.gcd(x, y);
  }

  public static int gcdmain(String[] argc) {
    return exampleJNI.gcdmain(argc);
  }

  public static int count(String bytes, char c) {
    return exampleJNI.count(bytes, c);
  }

  public static void capitalize(String[] str) {
    exampleJNI.capitalize(str);
  }

  public static void circle(double cx, double cy) {
    exampleJNI.circle(cx, cy);
  }

}
