/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package template_partial_specialization;

public class ThreeParmInt {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ThreeParmInt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ThreeParmInt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        template_partial_specializationJNI.delete_ThreeParmInt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void a2() {
    template_partial_specializationJNI.ThreeParmInt_a2(swigCPtr, this);
  }

  public ThreeParmInt() {
    this(template_partial_specializationJNI.new_ThreeParmInt(), true);
  }

}
