/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package template_classes;

public class RectangleInt {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RectangleInt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RectangleInt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        template_classesJNI.delete_RectangleInt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PointInt getPoint() {
    return new PointInt(template_classesJNI.RectangleInt_getPoint(swigCPtr, this), false);
  }

  public void setPoint(PointInt value) {
    template_classesJNI.RectangleInt_setPoint(swigCPtr, this, PointInt.getCPtr(value), value);
  }

  public RectangleInt() {
    this(template_classesJNI.new_RectangleInt(), true);
  }

}
