/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package constructor_copy;

public class FlowFlow {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FlowFlow(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FlowFlow obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        constructor_copyJNI.delete_FlowFlow(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FlowFlow(int i) {
    this(constructor_copyJNI.new_FlowFlow__SWIG_0(i), true);
  }

  public FlowFlow(FlowFlow other) {
    this(constructor_copyJNI.new_FlowFlow__SWIG_1(FlowFlow.getCPtr(other), other), true);
  }

}
