/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package char_constant;

public interface char_constantConstants {
  public final static char CHAR_CONSTANT = char_constantJNI.CHAR_CONSTANT_get();
  public final static String STRING_CONSTANT = char_constantJNI.STRING_CONSTANT_get();
  public final static char ESC_CONST = char_constantJNI.ESC_CONST_get();
  public final static char NULL_CONST = char_constantJNI.NULL_CONST_get();
  public final static char SPECIALCHAR = char_constantJNI.SPECIALCHAR_get();
}
