/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package access_change;

public class access_changeJNI {
  public final static native void delete_BaseInt(long jarg1);
  public final static native long BaseInt_PublicProtectedPublic1(long jarg1, BaseInt jarg1_);
  public final static native long BaseInt_PublicProtectedPublic2(long jarg1, BaseInt jarg1_);
  public final static native long BaseInt_PublicProtectedPublic3(long jarg1, BaseInt jarg1_);
  public final static native long BaseInt_PublicProtectedPublic4(long jarg1, BaseInt jarg1_);
  public final static native long new_BaseInt();
  public final static native long DerivedInt_WasProtected1(long jarg1, DerivedInt jarg1_);
  public final static native long DerivedInt_WasProtected2(long jarg1, DerivedInt jarg1_);
  public final static native long DerivedInt_WasProtected3(long jarg1, DerivedInt jarg1_);
  public final static native long DerivedInt_WasProtected4(long jarg1, DerivedInt jarg1_);
  public final static native long new_DerivedInt();
  public final static native void delete_DerivedInt(long jarg1);
  public final static native long BottomInt_WasProtected1(long jarg1, BottomInt jarg1_);
  public final static native long BottomInt_WasProtected2(long jarg1, BottomInt jarg1_);
  public final static native long BottomInt_WasProtected3(long jarg1, BottomInt jarg1_);
  public final static native long BottomInt_WasProtected4(long jarg1, BottomInt jarg1_);
  public final static native long BottomInt_PublicProtectedPublic1(long jarg1, BottomInt jarg1_);
  public final static native long BottomInt_PublicProtectedPublic2(long jarg1, BottomInt jarg1_);
  public final static native long BottomInt_PublicProtectedPublic3(long jarg1, BottomInt jarg1_);
  public final static native long BottomInt_PublicProtectedPublic4(long jarg1, BottomInt jarg1_);
  public final static native long new_BottomInt();
  public final static native void delete_BottomInt(long jarg1);
  public final static native long DerivedInt_SWIGUpcast(long jarg1);
  public final static native long BottomInt_SWIGUpcast(long jarg1);
}
