/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


int globalVar = 0;

namespace Space {
  typedef struct tagAStruct {
    int ivar;
  } AStruct;

  struct BStruct {
    int ivar;
  };

  typedef struct tagCStruct {
    int ivar;
  } CStruct;

  // Unnamed struct
  typedef struct {
    int ivar;
  } DStruct;

}

typedef struct tagEStruct {
  int ivar;
} EStruct;

namespace Space {
  template<typename T>
  struct FFStruct {
    int ivar;
  };
}

SWIGINTERN Space::tagAStruct *new_Space_tagAStruct(int ivar0){
    Space::AStruct *s = new Space::AStruct();
    s->ivar = ivar0;
    globalVar = ivar0;
    return s;
  }
SWIGINTERN void delete_Space_tagAStruct(Space::tagAStruct *self){
    globalVar = -self->ivar;
    delete self;
  }
SWIGINTERN Space::BStruct *new_Space_BStruct(int ivar0){
    Space::BStruct *s = new Space::BStruct();
    s->ivar = ivar0;
    globalVar = ivar0;
    return s;
  }
SWIGINTERN void delete_Space_BStruct(Space::BStruct *self){
    globalVar = -self->ivar;
    delete self;
  }
SWIGINTERN Space::tagCStruct *new_Space_tagCStruct(int ivar0){
    Space::CStruct *s = new Space::CStruct();
    s->ivar = ivar0;
    globalVar = ivar0;
    return s;
  }
SWIGINTERN void delete_Space_tagCStruct(Space::tagCStruct *self){
    globalVar = -self->ivar;
    delete self;
  }
SWIGINTERN Space::DStruct *new_Space_DStruct(int ivar0){
    Space::DStruct *s = new Space::DStruct();
    s->ivar = ivar0;
    globalVar = ivar0;
    return s;
  }
SWIGINTERN void delete_Space_DStruct(Space::DStruct *self){
    globalVar = -self->ivar;
    delete self;
  }
SWIGINTERN tagEStruct *new_tagEStruct(int ivar0){
    EStruct *s = new EStruct();
    s->ivar = ivar0;
    globalVar = ivar0;
    return s;
  }
SWIGINTERN void delete_tagEStruct(tagEStruct *self){
    globalVar = -self->ivar;
    delete self;
  }
SWIGINTERN Space::FFStruct< long > *new_Space_FFStruct_Sl_long_Sg_(int ivar0){
    Space::FFStruct<long> *s = new Space::FFStruct<long>();
    s->ivar = ivar0;
    globalVar = ivar0;
    return s;
  }
SWIGINTERN void delete_Space_FFStruct_Sl_long_Sg_(Space::FFStruct< long > *self){
    globalVar = -self->ivar;
    delete self;
  }
SWIGINTERN Space::FFStruct< char > *new_Space_FFStruct_Sl_char_Sg_(int ivar0){
    Space::FFStruct<char> *s = new Space::FFStruct<char>();
    s->ivar = ivar0;
    globalVar = ivar0;
    return s;
  }
SWIGINTERN void delete_Space_FFStruct_Sl_char_Sg_(Space::FFStruct< char > *self){
    globalVar = -self->ivar;
    delete self;
  }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_globalVar_1set(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  globalVar = arg1;
}


SWIGEXPORT jint JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_globalVar_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)globalVar;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_AStruct_1ivar_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Space::tagAStruct *arg1 = (Space::tagAStruct *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Space::tagAStruct **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->ivar = arg2;
}


SWIGEXPORT jint JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_AStruct_1ivar_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Space::tagAStruct *arg1 = (Space::tagAStruct *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Space::tagAStruct **)&jarg1; 
  result = (int) ((arg1)->ivar);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_new_1AStruct(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  Space::tagAStruct *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (Space::tagAStruct *)new_Space_tagAStruct(arg1);
  *(Space::tagAStruct **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_delete_1AStruct(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Space::tagAStruct *arg1 = (Space::tagAStruct *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Space::tagAStruct **)&jarg1; 
  delete_Space_tagAStruct(arg1);
}


SWIGEXPORT void JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_BStruct_1ivar_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Space::BStruct *arg1 = (Space::BStruct *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Space::BStruct **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->ivar = arg2;
}


SWIGEXPORT jint JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_BStruct_1ivar_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Space::BStruct *arg1 = (Space::BStruct *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Space::BStruct **)&jarg1; 
  result = (int) ((arg1)->ivar);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_new_1BStruct(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  Space::BStruct *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (Space::BStruct *)new_Space_BStruct(arg1);
  *(Space::BStruct **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_delete_1BStruct(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Space::BStruct *arg1 = (Space::BStruct *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Space::BStruct **)&jarg1; 
  delete_Space_BStruct(arg1);
}


SWIGEXPORT void JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_CStruct_1ivar_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Space::tagCStruct *arg1 = (Space::tagCStruct *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Space::tagCStruct **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->ivar = arg2;
}


SWIGEXPORT jint JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_CStruct_1ivar_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Space::tagCStruct *arg1 = (Space::tagCStruct *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Space::tagCStruct **)&jarg1; 
  result = (int) ((arg1)->ivar);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_new_1CStruct(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  Space::tagCStruct *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (Space::tagCStruct *)new_Space_tagCStruct(arg1);
  *(Space::tagCStruct **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_delete_1CStruct(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Space::tagCStruct *arg1 = (Space::tagCStruct *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Space::tagCStruct **)&jarg1; 
  delete_Space_tagCStruct(arg1);
}


SWIGEXPORT void JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_DStruct_1ivar_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Space::DStruct *arg1 = (Space::DStruct *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Space::DStruct **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->ivar = arg2;
}


SWIGEXPORT jint JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_DStruct_1ivar_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Space::DStruct *arg1 = (Space::DStruct *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Space::DStruct **)&jarg1; 
  result = (int) ((arg1)->ivar);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_new_1DStruct(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  Space::DStruct *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (Space::DStruct *)new_Space_DStruct(arg1);
  *(Space::DStruct **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_delete_1DStruct(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Space::DStruct *arg1 = (Space::DStruct *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Space::DStruct **)&jarg1; 
  delete_Space_DStruct(arg1);
}


SWIGEXPORT void JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_EStruct_1ivar_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  tagEStruct *arg1 = (tagEStruct *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(tagEStruct **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->ivar = arg2;
}


SWIGEXPORT jint JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_EStruct_1ivar_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  tagEStruct *arg1 = (tagEStruct *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(tagEStruct **)&jarg1; 
  result = (int) ((arg1)->ivar);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_new_1EStruct(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  tagEStruct *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (tagEStruct *)new_tagEStruct(arg1);
  *(tagEStruct **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_delete_1EStruct(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  tagEStruct *arg1 = (tagEStruct *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(tagEStruct **)&jarg1; 
  delete_tagEStruct(arg1);
}


SWIGEXPORT void JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_FStruct_1ivar_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Space::FFStruct< long > *arg1 = (Space::FFStruct< long > *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Space::FFStruct< long > **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->ivar = arg2;
}


SWIGEXPORT jint JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_FStruct_1ivar_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Space::FFStruct< long > *arg1 = (Space::FFStruct< long > *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Space::FFStruct< long > **)&jarg1; 
  result = (int) ((arg1)->ivar);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_new_1FStruct(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  Space::FFStruct< long > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (Space::FFStruct< long > *)new_Space_FFStruct_Sl_long_Sg_(arg1);
  *(Space::FFStruct< long > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_delete_1FStruct(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Space::FFStruct< long > *arg1 = (Space::FFStruct< long > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Space::FFStruct< long > **)&jarg1; 
  delete_Space_FFStruct_Sl_long_Sg_(arg1);
}


SWIGEXPORT void JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_GStruct_1ivar_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Space::FFStruct< char > *arg1 = (Space::FFStruct< char > *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Space::FFStruct< char > **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->ivar = arg2;
}


SWIGEXPORT jint JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_GStruct_1ivar_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Space::FFStruct< char > *arg1 = (Space::FFStruct< char > *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Space::FFStruct< char > **)&jarg1; 
  result = (int) ((arg1)->ivar);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_new_1GStruct(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  Space::FFStruct< char > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (Space::FFStruct< char > *)new_Space_FFStruct_Sl_char_Sg_(arg1);
  *(Space::FFStruct< char > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_extend_1constructor_1destructor_extend_1constructor_1destructorJNI_delete_1GStruct(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Space::FFStruct< char > *arg1 = (Space::FFStruct< char > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Space::FFStruct< char > **)&jarg1; 
  delete_Space_FFStruct_Sl_char_Sg_(arg1);
}


#ifdef __cplusplus
}
#endif

