/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package director_keywords;

public class director_keywordsJNI {
  public final static native void delete_Foo(long jarg1);
  public final static native void Foo_bar(long jarg1, Foo jarg1_, int jarg2);
  public final static native void Foo_barSwigExplicitFoo(long jarg1, Foo jarg1_, int jarg2);
  public final static native long new_Foo();
  public final static native void Foo_director_connect(Foo obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void Foo_change_ownership(Foo obj, long cptr, boolean take_or_release);

  public static void SwigDirector_Foo_bar(Foo self, int arg0) {
    self.bar(arg0);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
