/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package enum_thorough;

public class Instances {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Instances(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Instances obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enum_thoroughJNI.delete_Instances(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMemberInstance(int value) {
    enum_thoroughJNI.Instances_MemberInstance_set(swigCPtr, this, value);
  }

  public int getMemberInstance() {
    return enum_thoroughJNI.Instances_MemberInstance_get(swigCPtr, this);
  }

  public Instances() {
    this(enum_thoroughJNI.new_Instances(), true);
  }

  public final static int memberinstance1 = enum_thoroughJNI.Instances_memberinstance1_get();
  public final static int memberinstance2 = enum_thoroughJNI.Instances_memberinstance2_get();
  public final static int memberinstance3 = enum_thoroughJNI.Instances_memberinstance3_get();

}
