/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package enum_thorough;

public final class repeat {
  public final static repeat one = new repeat("one", 1);
  public final static repeat initial = new repeat("initial", one);
  public final static repeat two = new repeat("two");
  public final static repeat three = new repeat("three");
  public final static repeat llast = new repeat("llast", three);
  public final static repeat end = new repeat("end", llast);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static repeat swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + repeat.class + " with value " + swigValue);
  }

  private repeat(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private repeat(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private repeat(String swigName, repeat swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static repeat[] swigValues = { one, initial, two, three, llast, end };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

