/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package namespace_enum;

public class namespace_enumJNI {
  public final static native long new_Bar();
  public final static native void delete_Bar(long jarg1);
}
