/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package apply_signed_char;

public class apply_signed_char {
  public static byte CharValFunction(byte number) {
    return apply_signed_charJNI.CharValFunction(number);
  }

  public static byte CCharValFunction(byte number) {
    return apply_signed_charJNI.CCharValFunction(number);
  }

  public static byte CCharRefFunction(byte number) {
    return apply_signed_charJNI.CCharRefFunction(number);
  }

  public static void setGlobalchar(byte value) {
    apply_signed_charJNI.globalchar_set(value);
  }

  public static byte getGlobalchar() {
    return apply_signed_charJNI.globalchar_get();
  }

  public static byte getGlobalconstchar() {
    return apply_signed_charJNI.globalconstchar_get();
  }

}
