/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package director_nspacePackage;

public class director_nspaceJNI {
  public final static native long new_TopLevel_Bar_FooBar__SWIG_0();
  public final static native long new_TopLevel_Bar_FooBar__SWIG_1(long jarg1, director_nspacePackage.TopLevel.Bar.FooBar jarg1_);
  public final static native void delete_TopLevel_Bar_FooBar(long jarg1);
  public final static native String TopLevel_Bar_FooBar_FooBarDo(long jarg1, director_nspacePackage.TopLevel.Bar.FooBar jarg1_);
  public final static native void delete_TopLevel_Bar_Foo(long jarg1);
  public final static native String TopLevel_Bar_Foo_ping(long jarg1, director_nspacePackage.TopLevel.Bar.Foo jarg1_);
  public final static native String TopLevel_Bar_Foo_pingSwigExplicitFoo(long jarg1, director_nspacePackage.TopLevel.Bar.Foo jarg1_);
  public final static native String TopLevel_Bar_Foo_pong(long jarg1, director_nspacePackage.TopLevel.Bar.Foo jarg1_);
  public final static native String TopLevel_Bar_Foo_pongSwigExplicitFoo(long jarg1, director_nspacePackage.TopLevel.Bar.Foo jarg1_);
  public final static native String TopLevel_Bar_Foo_fooBar(long jarg1, director_nspacePackage.TopLevel.Bar.Foo jarg1_, long jarg2, director_nspacePackage.TopLevel.Bar.FooBar jarg2_);
  public final static native String TopLevel_Bar_Foo_fooBarSwigExplicitFoo(long jarg1, director_nspacePackage.TopLevel.Bar.Foo jarg1_, long jarg2, director_nspacePackage.TopLevel.Bar.FooBar jarg2_);
  public final static native long TopLevel_Bar_Foo_makeFoo(long jarg1, director_nspacePackage.TopLevel.Bar.Foo jarg1_);
  public final static native long TopLevel_Bar_Foo_makeFooSwigExplicitFoo(long jarg1, director_nspacePackage.TopLevel.Bar.Foo jarg1_);
  public final static native long TopLevel_Bar_Foo_makeFooBar(long jarg1, director_nspacePackage.TopLevel.Bar.Foo jarg1_);
  public final static native long TopLevel_Bar_Foo_makeFooBarSwigExplicitFoo(long jarg1, director_nspacePackage.TopLevel.Bar.Foo jarg1_);
  public final static native long TopLevel_Bar_Foo_get_self(long jarg1, director_nspacePackage.TopLevel.Bar.Foo jarg1_);
  public final static native long new_TopLevel_Bar_Foo();
  public final static native void TopLevel_Bar_Foo_director_connect(director_nspacePackage.TopLevel.Bar.Foo obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void TopLevel_Bar_Foo_change_ownership(director_nspacePackage.TopLevel.Bar.Foo obj, long cptr, boolean take_or_release);

  public static String TopLevel_Bar_SwigDirector_TopLevel_Bar_Foo_ping(director_nspacePackage.TopLevel.Bar.Foo self) {
    return self.ping();
  }
  public static String TopLevel_Bar_SwigDirector_TopLevel_Bar_Foo_pong(director_nspacePackage.TopLevel.Bar.Foo self) {
    return self.pong();
  }
  public static String TopLevel_Bar_SwigDirector_TopLevel_Bar_Foo_fooBar(director_nspacePackage.TopLevel.Bar.Foo self, long fb) {
    return self.fooBar((fb == 0) ? null : new director_nspacePackage.TopLevel.Bar.FooBar(fb, false));
  }
  public static long TopLevel_Bar_SwigDirector_TopLevel_Bar_Foo_makeFoo(director_nspacePackage.TopLevel.Bar.Foo self) {
    return director_nspacePackage.TopLevel.Bar.Foo.getCPtr(self.makeFoo());
  }
  public static long TopLevel_Bar_SwigDirector_TopLevel_Bar_Foo_makeFooBar(director_nspacePackage.TopLevel.Bar.Foo self) {
    return director_nspacePackage.TopLevel.Bar.FooBar.getCPtr(self.makeFooBar());
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
