/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package smart_pointer_templatevariables;

public class BasicString {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BasicString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BasicString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        smart_pointer_templatevariablesJNI.delete_BasicString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNpos(int value) {
    smart_pointer_templatevariablesJNI.BasicString_npos_set(swigCPtr, this, value);
  }

  public int getNpos() {
    return smart_pointer_templatevariablesJNI.BasicString_npos_get(swigCPtr, this);
  }

  public BasicString() {
    this(smart_pointer_templatevariablesJNI.new_BasicString(), true);
  }

}
