/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nspacePackage.Outer.Inner3;

public class Blue extends nspacePackage.Outer.Inner2.Color {
  private long swigCPtr;

  public Blue(long cPtr, boolean cMemoryOwn) {
    super(nspacePackage.nspaceJNI.Outer_Inner3_Blue_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Blue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nspacePackage.nspaceJNI.delete_Outer_Inner3_Blue(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void blueInstanceMethod() {
    nspacePackage.nspaceJNI.Outer_Inner3_Blue_blueInstanceMethod(swigCPtr, this);
  }

  public Blue() {
    this(nspacePackage.nspaceJNI.new_Outer_Inner3_Blue__SWIG_0(), true);
  }

  public Blue(nspacePackage.Outer.Inner3.Blue other) {
    this(nspacePackage.nspaceJNI.new_Outer_Inner3_Blue__SWIG_1(nspacePackage.Outer.Inner3.Blue.getCPtr(other), other), true);
  }

}
