/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package global_namespace;

public class TheEnumMethods {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TheEnumMethods(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TheEnumMethods obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        global_namespaceJNI.delete_TheEnumMethods(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void methodA(TheEnum1 v, TheEnum2 cv, TheEnum3 cr) {
    global_namespaceJNI.TheEnumMethods_methodA(v.swigValue(), cv.swigValue(), cr.swigValue());
  }

  public static void methodB(TheEnum1 v, TheEnum2 cv, TheEnum3 cr) {
    global_namespaceJNI.TheEnumMethods_methodB(v.swigValue(), cv.swigValue(), cr.swigValue());
  }

  public TheEnumMethods() {
    this(global_namespaceJNI.new_TheEnumMethods(), true);
  }

}
