/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package special_variable_macros;

public class special_variable_macrosJNI {
  public final static native long new_Name__SWIG_0(String jarg1);
  public final static native long new_Name__SWIG_1();
  public final static native long new_Name__SWIG_2(long jarg1, Name jarg1_);
  public final static native void delete_Name(long jarg1);
  public final static native String Name_getName(long jarg1, Name jarg1_);
  public final static native long Name_getNamePtr(long jarg1, Name jarg1_);
  public final static native long new_NameWrap__SWIG_0(String jarg1);
  public final static native long new_NameWrap__SWIG_1();
  public final static native long NameWrap_getNamePtr(long jarg1, NameWrap jarg1_);
  public final static native void delete_NameWrap(long jarg1);
  public final static native String testFred(long jarg1, Name jarg1_);
  public final static native String testJack(long jarg1, Name jarg1_);
  public final static native String testJill(long jarg1, Name jarg1_);
  public final static native String testMary(long jarg1, Name jarg1_);
  public final static native String testJames(long jarg1, Name jarg1_);
  public final static native String testJim(long jarg1, Name jarg1_);
  public final static native int testJohn(long jarg1, PairIntBool jarg1_);
  public final static native long new_PairIntBool__SWIG_0(int jarg1, boolean jarg2);
  public final static native long new_PairIntBool__SWIG_1();
  public final static native void PairIntBool_first_set(long jarg1, PairIntBool jarg1_, int jarg2);
  public final static native int PairIntBool_first_get(long jarg1, PairIntBool jarg1_);
  public final static native void PairIntBool_second_set(long jarg1, PairIntBool jarg1_, boolean jarg2);
  public final static native boolean PairIntBool_second_get(long jarg1, PairIntBool jarg1_);
  public final static native void delete_PairIntBool(long jarg1);
  public final static native long new_NewName(long jarg1, Name jarg1_);
  public final static native long NewName_getStoredName(long jarg1, NewName jarg1_);
  public final static native void delete_NewName(long jarg1);
}
