/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package template_namespace_forward_declaration;

public class template_namespace_forward_declaration {
  public static void testXXX1(XXXInt xx) {
    template_namespace_forward_declarationJNI.testXXX1(XXXInt.getCPtr(xx), xx);
  }

  public static void testXXX2(XXXInt xx) {
    template_namespace_forward_declarationJNI.testXXX2(XXXInt.getCPtr(xx), xx);
  }

  public static void testXXX3(XXXInt xx) {
    template_namespace_forward_declarationJNI.testXXX3(XXXInt.getCPtr(xx), xx);
  }

  public static void testYYY1(YYYInt yy) {
    template_namespace_forward_declarationJNI.testYYY1(YYYInt.getCPtr(yy), yy);
  }

  public static void testYYY2(YYYInt yy) {
    template_namespace_forward_declarationJNI.testYYY2(YYYInt.getCPtr(yy), yy);
  }

  public static void testYYY3(YYYInt yy) {
    template_namespace_forward_declarationJNI.testYYY3(YYYInt.getCPtr(yy), yy);
  }

}
