/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package abstract_typedef2;

public class A_UF extends Base_UF {
  private long swigCPtr;

  protected A_UF(long cPtr, boolean cMemoryOwn) {
    super(abstract_typedef2JNI.A_UF_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(A_UF obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        abstract_typedef2JNI.delete_A_UF(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public A_UF(int a) {
    this(abstract_typedef2JNI.new_A_UF__SWIG_0(a), true);
  }

  public A_UF() {
    this(abstract_typedef2JNI.new_A_UF__SWIG_1(), true);
  }

  public SWIGTYPE_p_FacetT_UnaryField_t set(long arg0) {
    long cPtr = abstract_typedef2JNI.A_UF_set(swigCPtr, this, arg0);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FacetT_UnaryField_t(cPtr, false);
  }

}
