/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package template_template_parameters;

public class ListDefaultDouble extends ListImplFastDouble {
  private long swigCPtr;

  protected ListDefaultDouble(long cPtr, boolean cMemoryOwn) {
    super(template_template_parametersJNI.ListDefaultDouble_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ListDefaultDouble obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        template_template_parametersJNI.delete_ListDefaultDouble(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setItem(double value) {
    template_template_parametersJNI.ListDefaultDouble_item_set(swigCPtr, this, value);
  }

  public double getItem() {
    return template_template_parametersJNI.ListDefaultDouble_item_get(swigCPtr, this);
  }

  public void xx() {
    template_template_parametersJNI.ListDefaultDouble_xx(swigCPtr, this);
  }

  public ListDefaultDouble() {
    this(template_template_parametersJNI.new_ListDefaultDouble(), true);
  }

}
