/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package li_attribute;

public class B {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected B(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(B obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        li_attributeJNI.delete_B(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public B(A a) {
    this(li_attributeJNI.new_B(A.getCPtr(a), a), true);
  }

  public void setA(A value) {
    li_attributeJNI.B_a_set(swigCPtr, this, A.getCPtr(value), value);
  }

  public A getA() {
    long cPtr = li_attributeJNI.B_a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new A(cPtr, false);
  }

}
