/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package return_value_scope;

public class return_value_scopeJNI {
  public final static native long new_Foo(int jarg1);
  public final static native void delete_Foo(long jarg1);
  public final static native long new_Bar();
  public final static native void delete_Bar(long jarg1);
  public final static native long Spam_test(long jarg1, Spam jarg1_);
  public final static native long new_Spam();
  public final static native void delete_Spam(long jarg1);
}
